import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../assets/styles/index.scss";
import "../globals.scss";
import "./loading.scss";
import { ConfigProvider, Layout } from "antd";
import TheFooter from "@/components/Misc.Header/Footer";
import TheHeader from "@/components/Misc.Header/Header";
import { Content } from "antd/es/layout/layout";

import StyledComponentsRegistry from "../../lib/AntdRegistry";
import theme from "./themeConfig";
import { ClerkLoaded, ClerkLoading, ClerkProvider } from "@clerk/nextjs";
import { NextIntlClientProvider } from "next-intl";
import { enUS, ruRU } from "@clerk/localizations";
import { getTranslations } from "next-intl/server";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return [{ locale: "en" }, { locale: "ru" }];
}

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: any;
}) {
  const messages = (await import(`../../../locales/${locale}.json`)).default;

  return (
    <NextIntlClientProvider locale={locale} messages={messages}>
      <ClerkProvider localization={locale == "ru" ? ruRU : enUS}>
        <html lang={locale}>
          <body suppressHydrationWarning={true} className={inter.className}>
            <StyledComponentsRegistry>
              <ConfigProvider theme={theme}>
                <LoadingComponent locale={locale} />
                <ClerkLoaded>
                  <Layout>
                    <TheHeader />
                    <Content style={{ padding: "0 0 " }}>{children}</Content>
                    <TheFooter />
                  </Layout>
                </ClerkLoaded>
              </ConfigProvider>
            </StyledComponentsRegistry>
          </body>
        </html>
      </ClerkProvider>
    </NextIntlClientProvider>
  );
}

async function LoadingComponent({ locale }: { locale: string }) {
  const t = await getTranslations({ locale, namespace: "Common" });
  const { colorPrimary } = theme.token!;

  return (
    <ClerkLoading>
      <div className="clerk-loading">
        <h1 style={{ color: colorPrimary }}>
          {t("loading")
            .split("")
            .map((c, i) => (
              <span key={i} className={`let${i + 1}`}>
                {c}
              </span>
            ))}
        </h1>
      </div>
    </ClerkLoading>
  );
}
